Fix home documentation : home-manager is a required input
In order to avoid the following error

```txt
error: In order to create home-manager configurations, you must include `home-manager` as a flake input.
```